name: angular-build
on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Node setup
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - run: npm ci
            - run: npm run build
            - run: git add dist
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: main
                folder: dist
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}