name: angular-build
on:
    push:
        branches: ["main", "master"]
    pull_request:
        branches: ["main", "master"]
    workflow_dispatch:

jobs:
    ubuntu-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Node setup
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - run: npm ci
            - run: npm run build
            - run: ls dist/
            - run: mv dist/mi-portfolio/browser dist/mi-portfolio/docs
            - run: cp dist/mi-portfolio/docs/index.html dist/mi-portfolio/docs/404.html
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: gh-pages
                folder: dist/mi-portfolio